CREATE TABLE supplier(
SNO TEXT PRIMARY KEY,
SNAME TEXT,
STATUS INTEGER,
CITY TEXT
);

INSERT INTO supplier(SNO,SNAME,STATUS,CITY) VALUES
('S1','RIYA',20,'LONDON'),
('S2','sIYA',30,'PARIS'),
('S3','BLAKE',50,'ATHENS'),
('S4','JOHN',10,'LONDON');

SELECT * FROM supplier where CITY=='LONDON';

DROP TABLE supplier;